<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>

    <IsPackable>false</IsPackable>

    <LangVersion>latest</LangVersion>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="app.config" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="nunit" Version="4.5.1" />
    <PackageReference Include="NUnit3TestAdapter" Version="6.2.0">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="18.4.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Examples\Example1\Example1.csproj" />
    <ProjectReference Include="..\..\Fibrous\Fibrous.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Properties\" />
  </ItemGroup>

</Project>
