<Project Sdk="Microsoft.NET.Sdk.WindowsDesktop">
  <PropertyGroup>
    <TargetFrameworks>net8.0-windows;net10.0-windows</TargetFrameworks>
    <DefineConstants>$(DefineConstants);WPF</DefineConstants>
    <Platforms>x64;x86;AnyCPU</Platforms>
    <UseWPF>true</UseWPF>
    <Title>Fibrous.WPF</Title>
    <Version>7.0.0</Version>
    <Description>High performace concurrency library for the .Net platform.</Description>
    <Authors>Chris Anderson</Authors>
    <Company>CA Anderson LLC</Company>
    <PackageProjectUrl>https://github.com/chrisa23/Fibrous</PackageProjectUrl>
    <RepositoryUrl>https://github.com/chrisa23/Fibrous</RepositoryUrl>
    <AssemblyVersion>7.0.0</AssemblyVersion>
    <FileVersion>7.0.0</FileVersion>
    <GeneratePackageOnBuild>false</GeneratePackageOnBuild>
    <PackageTags>concurrency actors multi-threading messaging</PackageTags>
    <LangVersion>latest</LangVersion>
    <PublishRepositoryUrl>true</PublishRepositoryUrl>
    <IncludeSymbols>true</IncludeSymbols>
    <SymbolPackageFormat>snupkg</SymbolPackageFormat>
    <ContinuousIntegrationBuild>true</ContinuousIntegrationBuild>
    <EmbedUntrackedSources>true</EmbedUntrackedSources>

    <PackageReadmeFile>README.md</PackageReadmeFile>
    <PackageLicenseFile>LICENSE.txt</PackageLicenseFile>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.SourceLink.GitHub" Version="10.0.201" PrivateAssets="All" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Fibrous\Fibrous.csproj"/>
  </ItemGroup>
  
  <ItemGroup>
    <None Include="../README.md" Pack="true" PackagePath=""/>
    <None Include="../LICENSE.txt" Pack="true" PackagePath=""/>
  </ItemGroup>
  
</Project>
